/*
 * This file is generated by jOOQ.
 */
package jooqtest;


import javax.annotation.Generated;

import jooqtest.tables.Employees;
import jooqtest.tables.Organizations;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EMPLOYEES_PKEY = Indexes0.EMPLOYEES_PKEY;
    public static final Index ORGANIZATIONS_PKEY = Indexes0.ORGANIZATIONS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EMPLOYEES_PKEY = Internal.createIndex("Employees_pkey", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.ID }, true);
        public static Index ORGANIZATIONS_PKEY = Internal.createIndex("Organizations_pkey", Organizations.ORGANIZATIONS, new OrderField[] { Organizations.ORGANIZATIONS.ID }, true);
    }
}
